from __future__ import annotations

import asyncio
import json
import uuid
from datetime import datetime
from typing import Any

from fastapi import (
    APIRouter,
    BackgroundTasks,
    Depends,
    HTTPException,
    WebSocket,
    WebSocketDisconnect,
    status,
)
from sqlalchemy.orm import Session

from app.db.models import (
    AgentOutput,
    ConfidenceScore,
    Incident,
    User,
)
from app.dependencies import (
    SessionLocal,
    get_db_session,
    require_engineer,
)
from app.diagnosis_jobs import (
    create_job,
    get_job,
    mark_completed,
    mark_failed,
    mark_running,
)
from app.diagnosis_events import (
    publish_event,
    subscribe,
    unsubscribe,
)
from app.graph import graph
from app.models.diagnosis import (
    DiagnosisAcceptedResponse,
    DiagnosisJobResponse,
    DiagnosisRequest,
)
from app.security import decode_access_token


router = APIRouter(
    prefix="/api/diagnosis",
    tags=["Diagnosis"],
)


def _json_text(value: Any) -> str | None:
    """
    Convert structured agent output into text suitable for
    the normalized agent_outputs table.
    """

    if value is None:
        return None

    if isinstance(value, str):
        return value

    return json.dumps(
        value,
        default=str,
        ensure_ascii=False,
    )


def _build_raw_inputs(
    incident: Incident,
    supplied_inputs: dict[str, Any] | None,
) -> dict[str, Any]:
    """
    Build the LangGraph raw_inputs payload.

    If the caller supplied raw observability data, preserve it.
    Otherwise construct a minimal payload from the stored incident.
    """

    if supplied_inputs is not None:
        raw_inputs = dict(supplied_inputs)

    else:
        raw_inputs = {}

    raw_inputs.setdefault("logs", [])
    raw_inputs.setdefault("metric_anomalies", [])
    raw_inputs.setdefault("trace", [])
    raw_inputs.setdefault("source_snippets", [])
    raw_inputs.setdefault("recent_commits", [])

    raw_inputs.setdefault(
        "incident_start",
        incident.created_at.isoformat()
        if incident.created_at
        else "",
    )

    raw_inputs.setdefault(
        "incident_end",
        incident.updated_at.isoformat()
        if incident.updated_at
        else "",
    )

    # Give the log agent at least the incident information when
    # no raw logs were supplied.
    if not raw_inputs["logs"]:
        raw_inputs["logs"] = [
            {
                "service": incident.source,
                "message": incident.description,
                "timestamp": (
                    incident.created_at.isoformat()
                    if incident.created_at
                    else None
                ),
            }
        ]

    return raw_inputs


def _persist_graph_result(
    db: Session,
    incident: Incident,
    agent_outputs: dict[str, Any],
) -> dict[str, Any]:
    """
    Persist every graph agent output and its confidence score.
    """

    persisted_outputs = {}

    for agent_name, output in agent_outputs.items():

        if not isinstance(output, dict):
            continue

        metadata = output.get("metadata") or {}

        agent_output = AgentOutput(
            incident_id=incident.incident_id,
            agent_name=agent_name,
            agent_type=agent_name,
            diagnosis=output.get("summary"),
            recommendation=_json_text(
                metadata.get("recommended_actions")
            ),
            reasoning=_json_text(output),
            created_at=datetime.utcnow(),
        )

        db.add(agent_output)
        db.flush()

        confidence = output.get("confidence")

        if confidence is not None:
            try:
                confidence_value = float(confidence)
            except (TypeError, ValueError):
                confidence_value = 0.0

            confidence_value = max(
                0.0,
                min(1.0, confidence_value),
            )

            confidence_score = ConfidenceScore(
                output_id=agent_output.output_id,
                score=confidence_value,
                confidence_level=(
                    "high"
                    if confidence_value >= 0.8
                    else "medium"
                    if confidence_value >= 0.5
                    else "low"
                ),
                explanation=output.get("summary"),
                created_at=datetime.utcnow(),
            )

            db.add(confidence_score)

        persisted_outputs[agent_name] = output

    return persisted_outputs


def _extract_final_report(
    agent_outputs: dict[str, Any],
) -> dict[str, Any]:
    """
    Extract the final report generated by the reasoning agent.
    """

    reasoning_output = agent_outputs.get(
        "reasoning_agent",
        {},
    )

    final_report = {}

    if isinstance(reasoning_output, dict):

        metadata = reasoning_output.get(
            "metadata",
            {},
        )

        if isinstance(metadata, dict):

            final_report = metadata.get(
                "final_report",
                {},
            )

    if not isinstance(final_report, dict):
        final_report = {}

    return final_report


def _run_diagnosis_background(
    job_id: str,
    incident_id: uuid.UUID,
    raw_inputs: dict[str, Any],
) -> None:
    """
    Execute the expensive LangGraph RCA pipeline in the background.

    A completely separate SQLAlchemy session is used because the
    request-scoped database session is already closed when this
    background task executes.
    """

    mark_running(job_id)

    # Notify WebSocket clients that processing has started.
    publish_event(
        job_id,
        "diagnosis_started",
        status="running",
    )

    db: Session = SessionLocal()

    try:
        incident = db.get(
            Incident,
            incident_id,
        )

        if incident is None:
            raise RuntimeError(
                "Incident no longer exists."
            )

        graph_inputs = {
            "raw_inputs": raw_inputs,
            "agent_outputs": {},
            "job_id": job_id,
        }

        graph_result = graph.invoke(
            graph_inputs
        )

        agent_outputs = graph_result.get(
            "agent_outputs",
            {},
        )

        if not isinstance(agent_outputs, dict):
            raise RuntimeError(
                "Diagnosis pipeline returned an invalid result."
            )

        final_report = _extract_final_report(
            agent_outputs
        )

        persisted_outputs = _persist_graph_result(
            db=db,
            incident=incident,
            agent_outputs=agent_outputs,
        )

        incident.updated_at = datetime.utcnow()

        db.commit()

        mark_completed(
            job_id=job_id,
            report=final_report,
            agent_outputs=persisted_outputs,
        )

        # Notify WebSocket clients that the complete diagnosis finished.
        publish_event(
            job_id,
            "diagnosis_completed",
            status="completed",
            report=final_report,
        )

    except Exception as exc:
        db.rollback()

        mark_failed(
            job_id=job_id,
            error=str(exc),
        )

        # Notify WebSocket clients about the failure.
        publish_event(
            job_id,
            "diagnosis_failed",
            status="failed",
            error=str(exc),
        )

    finally:
        db.close()


@router.post(
    "",
    response_model=DiagnosisAcceptedResponse,
    status_code=status.HTTP_202_ACCEPTED,
)
def diagnose(
    request: DiagnosisRequest,
    background_tasks: BackgroundTasks,
    db: Session = Depends(get_db_session),
    current_user: User = Depends(require_engineer),
):
    """
    Start the multi-agent RCA pipeline asynchronously.

    The caller can either:

    1. provide an existing incident_id, or
    2. provide raw_inputs and user_id to create an incident.

    The endpoint returns immediately with a job_id.
    """

    # ============================================================
    # CASE 1: Existing incident
    # ============================================================

    if request.incident_id is not None:

        incident = db.get(
            Incident,
            request.incident_id,
        )

        if incident is None:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Incident not found",
            )

        raw_inputs = _build_raw_inputs(
            incident,
            request.raw_inputs,
        )

    # ============================================================
    # CASE 2: Raw payload
    # ============================================================

    else:

        if request.user_id is None:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=(
                    "Either incident_id or user_id with raw_inputs "
                    "must be provided."
                ),
            )

        user = db.get(
            User,
            request.user_id,
        )

        if user is None:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="User not found",
            )

        raw_inputs = dict(
            request.raw_inputs or {}
        )

        description = (
            request.description
            or raw_inputs.get("description")
            or "Incident created from diagnosis request."
        )

        title = (
            request.title
            or raw_inputs.get("title")
            or "RCA Diagnosis Incident"
        )

        severity = (
            request.severity
            or raw_inputs.get("severity")
            or "medium"
        )

        incident_status = (
            request.status
            or raw_inputs.get("status")
            or "open"
        )

        source = (
            request.source
            or raw_inputs.get("source")
        )

        incident = Incident(
            user_id=request.user_id,
            title=title,
            description=description,
            severity=severity,
            status=incident_status,
            source=source,
            created_at=datetime.utcnow(),
        )

        db.add(incident)
        db.flush()

        raw_inputs.setdefault("logs", [])
        raw_inputs.setdefault("metric_anomalies", [])
        raw_inputs.setdefault("trace", [])
        raw_inputs.setdefault("source_snippets", [])
        raw_inputs.setdefault("recent_commits", [])
        raw_inputs.setdefault("incident_start", "")
        raw_inputs.setdefault("incident_end", "")

    # ============================================================
    # Create job
    # ============================================================

    job_id = create_job(
        incident_id=incident.incident_id,
        user_id=current_user.user_id,
    )

    # Commit the incident before returning.
    #
    # This is especially important for newly-created incidents:
    # the background worker uses a separate database session.
    db.commit()

    # ============================================================
    # Schedule background execution
    # ============================================================

    background_tasks.add_task(
        _run_diagnosis_background,
        job_id,
        incident.incident_id,
        raw_inputs,
    )

    return {
        "status": "accepted",
        "job_id": job_id,
        "incident_id": incident.incident_id,
    }


@router.get(
    "/jobs/{job_id}",
    response_model=DiagnosisJobResponse,
)
def diagnosis_job_status(
    job_id: str,
    current_user: User = Depends(require_engineer),
):
    """
    Return the current status of a background diagnosis job.
    """

    job = get_job(job_id)

    if job is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Diagnosis job not found",
        )

    # Prevent one engineer from reading another user's job.
    if job["user_id"] != str(current_user.user_id):
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="You do not have access to this diagnosis job",
        )

    return {
        "job_id": job["job_id"],
        "status": job["status"],
        "incident_id": uuid.UUID(
            job["incident_id"]
        ),
        "report": job.get("report") or None,
        "agent_outputs": job.get("agent_outputs") or None,
        "error": job.get("error"),
    }

# ============================================================
# WEBSOCKET - REAL-TIME DIAGNOSIS UPDATES
# ============================================================

@router.websocket("/ws/{job_id}")
async def diagnosis_websocket(
    websocket: WebSocket,
    job_id: str,
):
    """
    Stream real-time diagnosis progress events for a job.

    Authentication:
        ws://host/api/diagnosis/ws/{job_id}?token=<JWT>

    Events:
        - job_status
        - diagnosis_started
        - agent_completed
        - diagnosis_completed
        - diagnosis_failed
    """

    # --------------------------------------------------------
    # 1. Accept the WebSocket connection first
    # --------------------------------------------------------

    await websocket.accept()

    # --------------------------------------------------------
    # 2. Read JWT from query parameter
    # --------------------------------------------------------

    token = websocket.query_params.get("token")

    if not token:
        await websocket.send_json(
            {
                "event": "error",
                "job_id": job_id,
                "message": "Authentication token is required",
            }
        )
        await websocket.close(code=1008)
        return

    # --------------------------------------------------------
    # 3. Validate JWT
    # --------------------------------------------------------

    try:
        payload = decode_access_token(token)

    except Exception:
        await websocket.send_json(
            {
                "event": "error",
                "job_id": job_id,
                "message": "Invalid or expired token",
            }
        )
        await websocket.close(code=1008)
        return

    user_id = payload.get("sub")

    if not user_id:
        await websocket.send_json(
            {
                "event": "error",
                "job_id": job_id,
                "message": "Invalid token subject",
            }
        )
        await websocket.close(code=1008)
        return

    # --------------------------------------------------------
    # 4. Verify job exists
    # --------------------------------------------------------

    job = get_job(job_id)

    if job is None:
        await websocket.send_json(
            {
                "event": "error",
                "job_id": job_id,
                "message": (
                    "Diagnosis job is not available in the "
                    "current server process."
                ),
            }
        )
        await websocket.close(code=1008)
        return

    # --------------------------------------------------------
    # 5. Verify job ownership
    # --------------------------------------------------------

    if job["user_id"] != str(user_id):
        await websocket.send_json(
            {
                "event": "error",
                "job_id": job_id,
                "message": "You are not authorized to access this job",
            }
        )
        await websocket.close(code=1008)
        return

    # --------------------------------------------------------
    # 6. Subscribe to job events
    # --------------------------------------------------------

    event_queue, history = subscribe(job_id)

    try:

        # ----------------------------------------------------
        # Send current job status
        # ----------------------------------------------------

        await websocket.send_json(
            {
                "event": "job_status",
                "job_id": job_id,
                "status": job["status"],
            }
        )

        # ----------------------------------------------------
        # Replay events that happened before connection
        # ----------------------------------------------------

        for event in history:
            await websocket.send_json(event)

        # ----------------------------------------------------
        # If already completed/failed, stop
        # ----------------------------------------------------

        if job["status"] in {
            "completed",
            "failed",
        }:
            return

        # ----------------------------------------------------
        # Wait for live events
        # ----------------------------------------------------

        while True:

            event = await asyncio.to_thread(
                event_queue.get
            )

            await websocket.send_json(event)

            # ------------------------------------------------
            # Stop after final diagnosis event
            # ------------------------------------------------

            if event["event"] in {
                "diagnosis_completed",
                "diagnosis_failed",
            }:
                break

    except WebSocketDisconnect:
        pass

    finally:
        unsubscribe(
            job_id,
            event_queue,
        )