from typing import TypedDict, Dict, Any, Optional


class AgentState(TypedDict, total=False):
    """
    Shared state used by all Adaptive MAS-RCA agents.
    """

    # Original incident/log/system information
    raw_inputs: Dict[str, Any]

    # Outputs generated by individual agents
    agent_outputs: Dict[str, Any]

    # Confidence scores generated by agents
    confidence: Dict[str, float]

    # Final RCA report
    final_report: Optional[str]

    # Unique execution identifier
    trace_id: str